# Generated by Django 5.0.6 on 2024-07-09 13:16

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OAB', models.CharField(max_length=10, verbose_name='OAB: ')),
                ('nome', models.CharField(help_text='Primeiro nome', max_length=10, verbose_name='Nome:')),
                ('sobrenome', models.CharField(help_text='Ultimo nome', max_length=10, verbose_name='Sobrenome:')),
                ('contato', models.CharField(help_text='Telefone para contato', max_length=11, verbose_name='Telefone: ')),
                ('status', models.CharField(blank=True, choices=[('c', 'Concluido'), ('a', 'Em aberto'), ('p', 'Em progresso')], default='a', help_text='Status da ocorrência!', max_length=1)),
            ],
            options={
                'ordering': ['OAB', 'nome', 'sobrenome', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=5, max_length=7, prefix='01', primary_key=True, serialize=False)),
                ('denuncia', models.TextField(help_text='Deixe um comentário sobre o ocorrido!', max_length=1000, verbose_name='Compartilhe a ocorrência: ')),
                ('dataDaDenuncia', models.DateField(blank=True, null=True, verbose_name='Data da ocorrência: ')),
                ('advogado', models.ForeignKey(help_text='Advogado responsável', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.advogados')),
            ],
            options={
                'ordering': ['id', 'denuncia', 'dataDaDenuncia'],
            },
        ),
    ]
