# Generated by Django 5.0.6 on 2024-07-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advogados',
            new_name='Advogado',
        ),
        migrations.RenameModel(
            old_name='Denuncias',
            new_name='Denuncia',
        ),
    ]
