# Generated by Django 5.0.6 on 2024-07-09 13:28

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_advogados_advogado_rename_denuncias_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=5, max_length=7, prefix='01', primary_key=True, serialize=False),
        ),
    ]
