# Generated by Django 5.0.6 on 2024-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_denuncia_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['id', 'tipoDeOcorrencia', 'denuncia', 'dataDaDenuncia']},
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tipoDeOcorrencia',
            field=models.CharField(blank=True, choices=[('s', 'Assedio Sexual'), ('m', 'Assédio Moral')], default='m', help_text='Tipo de ocorrência!', max_length=1),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='OAB',
            field=models.CharField(max_length=10, verbose_name='OAB'),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='contato',
            field=models.CharField(help_text='Telefone para contato', max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='nome',
            field=models.CharField(help_text='Primeiro nome', max_length=10, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='sobrenome',
            field=models.CharField(help_text='Ultimo nome', max_length=10, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='dataDaDenuncia',
            field=models.DateField(blank=True, null=True, verbose_name='Data da ocorrência'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='denuncia',
            field=models.TextField(help_text='Deixe um comentário sobre o ocorrido!', max_length=1000, verbose_name='Compartilhe a ocorrência'),
        ),
    ]
