# Generated by Django 5.0.6 on 2024-07-09 14:24

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_denuncia_options_denuncia_tipodeocorrencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['id_denuncia', 'tipoDeOcorrencia', 'denuncia', 'dataDaDenuncia']},
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='advogado',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='id',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='id_denuncia',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=5, max_length=7, prefix='01', primary_key=True, serialize=False, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipoDeOcorrencia',
            field=models.CharField(blank=True, choices=[('s', 'Assédio Sexual'), ('m', 'Assédio Moral')], default='m', help_text='Tipo de ocorrência!', max_length=1, verbose_name='Tipo de Ocorrência'),
        ),
    ]
