# Generated by Django 5.0.6 on 2024-07-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_denuncia_options_remove_denuncia_advogado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advogado',
            options={'ordering': ['OAB', 'nome', 'sobrenome']},
        ),
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['id_denuncia', 'tipoDeOcorrencia', 'denuncia', 'dataDaDenuncia', 'status']},
        ),
        migrations.RemoveField(
            model_name='advogado',
            name='status',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'Concluido'), ('a', 'Em aberto'), ('p', 'Em progresso')], default='a', help_text='Status da ocorrência!', max_length=1),
        ),
    ]
