# Generated by Django 5.0.6 on 2024-07-09 20:32

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_casoparaadv_delete_denuncia'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroDeOcorrencia',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=5, max_length=7, prefix='01', primary_key=True, serialize=False, verbose_name='Senha')),
                ('tipoDeOcorrencia', models.CharField(blank=True, choices=[('s', 'Assédio Sexual'), ('m', 'Assédio Moral')], default='m', help_text='Tipo de ocorrência!', max_length=1, verbose_name='Tipo de Ocorrência')),
                ('registroDeCaso', models.TextField(help_text='Registre a ocorrência, que direcionaremos para um advogado!', max_length=1000, verbose_name='Registro de ocorrência')),
                ('dataDaDenuncia', models.DateField(blank=True, null=True, verbose_name='Data da ocorrência')),
                ('status', models.CharField(blank=True, choices=[('c', 'Concluido'), ('a', 'Em aberto'), ('p', 'Em progresso')], default='a', help_text='Status da ocorrência!', max_length=1)),
            ],
            options={
                'ordering': ['id', 'tipoDeOcorrencia', 'registroDeCaso', 'dataDaDenuncia', 'status'],
            },
        ),
    ]
