# Generated by Django 5.0.6 on 2024-07-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_registrodeocorrencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advogado',
            options={'ordering': ['OAB', 'nome', 'sobrenome', 'email']},
        ),
        migrations.RemoveField(
            model_name='advogado',
            name='contato',
        ),
        migrations.AddField(
            model_name='advogado',
            name='email',
            field=models.EmailField(default='default@example.com', help_text='Email para contato e acesso ao sistema', max_length=200, verbose_name='E-mail'),
        ),
    ]
