# Generated by Django 5.0.6 on 2024-07-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_advogado_options_remove_advogado_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoparaadv',
            name='advogado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.advogado'),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='email',
            field=models.EmailField(default='default@example.com', help_text='Email para contato e acesso ao sistema', max_length=200, unique=True, verbose_name='E-mail'),
        ),
    ]
