# Generated by Django 5.0.6 on 2024-07-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_casoparaadv_advogado_alter_advogado_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoparaadv',
            name='dataDaDenuncia',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Data da ocorrência'),
        ),
        migrations.AlterField(
            model_name='casoparaadv',
            name='registroDeCaso',
            field=models.TextField(editable=False, help_text='Registre a ocorrência, que direcionaremos para um advogado!', max_length=1000, verbose_name='Registro de ocorrência'),
        ),
        migrations.AlterField(
            model_name='casoparaadv',
            name='tipoDeOcorrencia',
            field=models.CharField(blank=True, choices=[('s', 'Assédio Sexual'), ('m', 'Assédio Moral')], default='m', editable=False, help_text='Tipo de ocorrência!', max_length=1, verbose_name='Tipo de Ocorrência'),
        ),
    ]
