# Generated by Django 5.0.6 on 2024-07-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_casoparaadv_datadadenuncia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoparaadv',
            name='tipoDeOcorrencia',
            field=models.CharField(blank=True, choices=[('Assédio Sexual', 'Assédio Sexual'), ('Assédio Moral', 'Assédio Moral')], default='Assédio Moral', editable=False, help_text='Tipo de ocorrência!', max_length=30, verbose_name='Tipo de Ocorrência'),
        ),
    ]
