# Generated by Django 5.0.6 on 2024-07-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_casoparaadv_tipodeocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoparaadv',
            name='advogado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.advogado'),
        ),
    ]
