# Generated by Django 5.0.6 on 2024-07-10 12:59

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_advogado_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=5, max_length=7, prefix='01', primary_key=True, serialize=False, verbose_name='Senha')),
                ('tipoDeOcorrencia', models.CharField(blank=True, choices=[('Assédio Sexual', 'Assédio Sexual'), ('Assédio Moral', 'Assédio Moral')], default='Assédio Moral', editable=False, help_text='Tipo de ocorrência!', max_length=30, verbose_name='Tipo de Ocorrência')),
                ('registroDeCaso', models.TextField(editable=False, help_text='Registre a ocorrência, que direcionaremos para um advogado!', max_length=1000, verbose_name='Registro de ocorrência')),
                ('dataDaDenuncia', models.DateField(blank=True, editable=False, null=True, verbose_name='Data da ocorrência')),
                ('status', models.CharField(blank=True, choices=[('c', 'Concluido'), ('a', 'Em aberto'), ('p', 'Em progresso')], default='a', help_text='Status da ocorrência!', max_length=1)),
                ('advogado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='API.advogado')),
            ],
            options={
                'ordering': ['id', 'tipoDeOcorrencia', 'registroDeCaso', 'dataDaDenuncia', 'status'],
            },
        ),
        migrations.AddField(
            model_name='advogado',
            name='ocorrencia',
            field=models.ManyToManyField(related_name='advogados', to='API.ocorrencia'),
        ),
        migrations.DeleteModel(
            name='CasoParaAdv',
        ),
    ]
