# Generated by Django 5.0.6 on 2024-07-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_ocorrencia_advogado_ocorrencia_delete_casoparaadv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='advogado',
        ),
        migrations.AddField(
            model_name='registrodeocorrencia',
            name='advogado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegistroDeOcorrencias', to='API.advogado'),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='ocorrencia',
            field=models.ManyToManyField(related_name='advogados', to='API.registrodeocorrencia'),
        ),
    ]
