# Generated by Django 5.0.6 on 2024-07-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_remove_ocorrencia_advogado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeocorrencia',
            name='advogado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_de_ocorrencia', to='API.advogado'),
        ),
        migrations.AlterField(
            model_name='registrodeocorrencia',
            name='status',
            field=models.CharField(blank=True, choices=[('Concluido', 'Concluido'), ('Em aberto', 'Em aberto'), ('Em progresso', 'Em progresso')], default='Em aberto', help_text='Status da ocorrência!', max_length=50),
        ),
    ]
