# Generated by Django 5.0.6 on 2024-07-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_alter_registrodeocorrencia_advogado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ocorrencia',
        ),
        migrations.RenameField(
            model_name='advogado',
            old_name='ocorrencia',
            new_name='registros_de_ocorrencia',
        ),
        migrations.AlterField(
            model_name='registrodeocorrencia',
            name='advogado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_de_ocorrencias', to='API.advogado'),
        ),
    ]
