# Generated by Django 5.0.6 on 2024-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_delete_ocorrencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advogado',
            options={'ordering': ['OAB', 'nome', 'sobrenome', 'email', 'user']},
        ),
        migrations.AlterField(
            model_name='advogado',
            name='registros_de_ocorrencia',
            field=models.ManyToManyField(blank=True, related_name='advogados', to='API.registrodeocorrencia'),
        ),
    ]
