# Generated by Django 5.0.6 on 2024-07-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_alter_advogado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advogado',
            options={'ordering': ['OAB', 'nome', 'sobrenome', 'email']},
        ),
        migrations.RemoveField(
            model_name='advogado',
            name='user',
        ),
    ]
